server {
    listen 80;
    server_name localhost;

    #负责处理 Vue 的前端静态网页
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 防止 Vue 路由刷新后报 404
        try_files $uri $uri/ /index.html; 
    }

    #拦截所有 /api 开头的请求，转发给后端的 fastapi 容器
    location /api/ {
        # 注意这里的 'api' 是 docker-compose.yml 里后端服务的名字
        proxy_pass http://api:8000/api/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}